# --- VÍDEO E HARDWARE ---
vo=gpu
gpu-context=wayland
hwdec=vaapi

# --- YOUTUBE EM 720P (Economia de 55% de processamento) ---
ytdl-format="bestvideo[height<=?720][vcodec^=avc1]+bestaudio/best[height<=?720]"
ytdl-raw-options=cookies-from-browser=firefox

# --- MELHORIA GRÁFICA PARA 720P ---
# Upscaling leve e sem serrilhados para adaptar o 720p à sua tela
scale=spline36
cscale=mitchell
dscale=mitchell

# Adiciona nitidez para compensar a resolução sem pesar na placa
sharpen=0.3

# Deband otimizado (apenas 1 iteração) para remover artefatos de cor do YouTube
deband=yes
deband-iterations=2
deband-threshold=35
deband-range=16
deband-grain=16

dither-depth=auto

# --- GERENCIAMENTO DE MEMÓRIA ---
demuxer-max-bytes=100M
demuxer-readahead-secs=20

screenshot-jpeg-quality=100

[TTRPG]
profile-cond=path:find('ttrpg')
save-position-on-quit=yes
