# Navegar na playlist de busca (Vídeo Anterior / Próximo)
Ctrl+RIGHT playlist-next
Ctrl+LEFT  playlist-prev

# Também mantemos as teclas originais forçadas (vírgula e ponto)
. playlist-next
, playlist-prev

# Exibir a lista/playlist na tela (OSD)
L show-text "${playlist}" 3000
p show-text "${playlist}" 3000

